# Generated by Django 4.2.6 on 2023-10-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='место')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.PositiveSmallIntegerField(default=1, verbose_name='периодичность')),
                ('reward', models.CharField(max_length=255, verbose_name='вознаграждение')),
                ('duration', models.PositiveIntegerField(default=120, verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
